## The test container is created with https://github.com/dracutdevs/fedora-container

name: Fedora-latest

on:
  push:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: quay.io/haraldh/dracut-fedora:latest
      options: "-v /dev/kvm:/dev/kvm"
    timeout-minutes: 45
    strategy:
      matrix:
        test: [
          "01",
          "02",
          "03",
          "04",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "17",
          "20",
          "21",
          "30",
          "31",
          "35",
          "36",
          "40",
          "41",
        ]
      fail-fast: false
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "TEST-${{ matrix.test }}"
        run: ./fedora-test-github.sh "TEST-${{ matrix.test }}" ${{ matrix.test }}
