name: Test

on:
    pull_request:
        branches: [ master ]

env:
    DEBUGFAIL: "${{ secrets.ACTIONS_STEP_DEBUG && 'rd.debug' }}"

jobs:
    test:
        name: ${{ matrix.test }} on ${{ matrix.container }}
        runs-on: ubuntu-latest
        timeout-minutes: 30
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.container }}-${{ matrix.test }}
            cancel-in-progress: true
        strategy:
            matrix:
                container: [
                        "arch",
                        "debian",
                        "fedora",
                        "opensuse",
                ]
                test: [
                        "01",
                        "02",
                        "03",
                        "04",
                        "10",
                        "11",
                        "12",
                        "13",
                        "14",
                        "15",
                        "16",
                        "17",
                        "62",
                        "98",
                ]
            fail-fast: false
        container:
            image: ghcr.io/dracutdevs/${{ matrix.container }}
            options: "--privileged -v /dev:/dev"
        steps:
            -   name: "Checkout Repository"
                uses: actions/checkout@v3
                with:
                    fetch-depth: 0

            -   name: "${{ matrix.container }} TEST-${{ matrix.test }}"
                run: ./tools/test-github.sh "TEST-${{ matrix.test }}" ${{ matrix.test }}
    network:
        name: ${{ matrix.test }} on ${{ matrix.container }} using ${{ matrix.network }}
        runs-on: ubuntu-latest
        timeout-minutes: 45
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.container }}-${{ matrix.test }}-${{ matrix.network }}
            cancel-in-progress: true
        strategy:
            matrix:
                container: [
                        "fedora",
                ]
                network: [
                        "network-manager",
                        "network-legacy",
                        #"systemd-networkd",
                        #"connman",
                ]
                test: [
                        "20",
                        "30",
                        "35",
                        "40",
                        "60",
                        # "50", # times out
                ]
            fail-fast: false
        container:
            image: ghcr.io/dracutdevs/${{ matrix.container }}
            options: "--privileged -v /dev:/dev"
        steps:
            -   name: "Checkout Repository"
                uses: actions/checkout@v3
                with:
                    fetch-depth: 0

            -   name: "${{ matrix.container }} TEST-${{ matrix.test }}"
                run: USE_NETWORK=${{ matrix.network }} ./tools/test-github.sh "TEST-${{ matrix.test }}" ${{ matrix.test }}
    openrc-musl:
        name: ${{ matrix.test }} on ${{ matrix.container }}
        runs-on: ubuntu-latest
        timeout-minutes: 45
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.container }}-${{ matrix.test }}
            cancel-in-progress: true
        strategy:
            matrix:
                container: [
                        "gentoo",
                ]
                test: [
                        "16",
                ]
            fail-fast: false
        container:
            image: ghcr.io/dracutdevs/${{ matrix.container }}
            options: "--privileged -v /dev:/dev"
        steps:
            -   name: "Checkout Repository"
                uses: actions/checkout@v1
                with:
                    fetch-depth: 0

            -   name: "${{ matrix.container }} TEST-${{ matrix.test }}"
                run: ./tools/test-github.sh "TEST-${{ matrix.test }}" ${{ matrix.test }}
