name: Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint-shell:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: shfmt
        uses: luizm/action-sh-checker@v0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHFMT_OPTS: -s # arguments to shfmt.
        with:
          sh_checker_shellcheck_disable: false
          sh_checker_comment: true

  lint-c:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install tools
        run: sudo apt-get install astyle

      - name: indent
        run: make indent-c

      - name: check formatting
        run: git diff --exit-code
